add raspi ubuntu and bulleye support

diff --git a/xdocker-create b/xdocker-create
--- a/xdocker-create
+++ b/xdocker-create
@@ -29,23 +29,35 @@
 
 set -Eeuo pipefail
 
+SCRIPT_SELF="$(realpath "${BASH_SOURCE[0]}")"
+# shellcheck disable=SC2034 # appears unused
+SCRIPT_DIR=$(dirname "${SCRIPT_SELF}")
+SCRIPT_FILE=$(basename "${SCRIPT_SELF}")
+# shellcheck disable=SC2034 # appears unused
+SCRIPT_NAME=$(basename -s .bash "$(basename -s .sh "${SCRIPT_FILE}")")
+
 # shellcheck disable=SC2034
 XDOCKER_MAKE_BASE_VERSION="1.0"
 XDOCKER_MAKE_VERSION=development
 
 function log() {
-        echo >&2 -e "[$(date +"%Y-%m-%d %H:%M:%S")] ${1-}"
+	echo >&2 -e "[$(date +"%Y-%m-%d %H:%M:%S")] ${1-}"
 }
 function die() {
-        local msg=$1
-        local code=${2-1} # Bash parameter expansion - default exit status 1. See https://wiki.bash-hackers.org/syntax/pe#use_a_default_value
-        log "$msg"
+	local msg=$1
+	local code=${2-1} # Bash parameter expansion - default exit status 1. See https://wiki.bash-hackers.org/syntax/pe#use_a_default_value
+	log "$msg"
 	if [ "$code" -ne 0 ]; then
 		log "💥 Error!"
 	fi
-        exit "$code"
+	exit "$code"
 }
-
+ifIsSet() {
+	[[ ${!1-x} == x ]] && return 1 || return 0
+}
+ifNotSet() {
+	[[ ${!1-x} == x ]] && return 0 || return 1
+}
 
 argc=$#
 if [ ${argc} -ne 1 ]; then
@@ -54,17 +66,14 @@ if [ ${argc} -ne 1 ]; then
 	exit 1
 fi
 
+if ifNotSet OUTPUT_DIR ; then
+OUTPUT_DIR=.
+fi
+
 CONFIG_FILE=${1}
 
 # shellcheck source=/dev/null
 source "${CONFIG_FILE}"
-
-ifIsSet() {
-	[[ ${!1-x} == x ]] && return 1 || return 0
-}
-ifNotSet() {
-	[[ ${!1-x} == x ]] && return 0 || return 1
-}
 
 # check required params and arguments
 ifNotSet OS_DISTRO && die "💥 OS_DISTRO was not defined."
@@ -77,10 +86,14 @@ ifNotSet DEB_PACKAGES && die "💥 DEB_PACKAGES was not defined."
 function cleanup() {
 	exit_code=$?
 	trap - SIGINT SIGTERM ERR EXIT
+
+	[[ $(type -t xdocker_conf_cleanup) == function ]] && xdocker_conf_cleanup
+
 	if [ -d "${tmpdir}" ]; then
 		rm -rf "$tmpdir"
 		log "🚽 Deleted temporary working directory $tmpdir"
 	fi
+
 	log "🚽 cleanup"
 	if [ $exit_code -ne 0 ]; then
 		log "💥 Error!"
@@ -89,18 +102,13 @@ function cleanup() {
 
 trap cleanup SIGINT SIGTERM ERR EXIT
 
-SCRIPT_DIR=$(dirname "$(realpath "${BASH_SOURCE[0]}")")
-if ifNotSet OUTPUT_DIR ; then
-OUTPUT_DIR=.
-fi
-
 log "👶 Starting up..."
 
 tmpdir=$(mktemp -d -p ${OUTPUT_DIR})
 if [[ ! "$tmpdir" || ! -d "$tmpdir" ]]; then
-        die "💥 Could not create temporary working directory."
+	die "💥 Could not create temporary working directory."
 else
-        log "📁 Created temporary working directory $tmpdir"
+	log "📁 Created temporary working directory $tmpdir"
 fi
 
 if [ "${XDOCKER_MAKE_VERSION}" == "development" ]; then
@@ -114,11 +122,14 @@ fi
 cp ${XDOCKER_IMAGE_CREATE} "$tmpdir/xdocker-image-create.bash"
 cp ${XDOCKER_BUILD_PROJECT} "$tmpdir/xdocker-build-project.bash"
 
+[[ $(type -t xdocker_make_config) == function ]] && xdocker_make_config "$tmpdir"
+
 cat > "$tmpdir/Dockerfile" << EOF
-FROM ${OS_NAME}:${OS_DISTRO}
+FROM ${DOCKER_FROM}
 
 MAINTAINER ${MAINTAINER}
 
+ENV OS_NAME=${OS_NAME}
 ENV OS_DISTRO=${OS_DISTRO}
 ENV IMAGE_TYPE=${IMAGE_TYPE}
 ENV CONTAINER_NAME=${CONTAINER_NAME}
@@ -133,6 +144,9 @@ LABEL OS_DISTRO=${OS_DISTRO}
 LABEL CONTAINER_NAME=${CONTAINER_NAME}
 LABEL CONTAINER_VERSION=${CONTAINER_VERSION}
 
+# extra tags from config
+${DOCKERFILE_TAGS:=}
+
 # copy setup script
 COPY ./xdocker-image-create.bash /
 COPY ./xdocker-build-project.bash /
@@ -144,10 +158,9 @@ ENTRYPOINT ["/bin/bash"]
 
 EOF
 
-cd "$tmpdir"
-docker build . --file "Dockerfile" \
+log "🔧 Create docker image"
+${SUDO:=} docker build "$tmpdir" --file "$tmpdir/Dockerfile" \
 	--tag "${CONTAINER_NAME}:${CONTAINER_TAG}" \
 	--tag "${CONTAINER_NAME}:latest"
-cd -
 
 die "✅ Completed." 0
diff --git a/xdocker-make b/xdocker-make
--- a/xdocker-make
+++ b/xdocker-make
@@ -35,16 +35,16 @@ XDOCKER_MAKE_BASE_VERSION="1.0"
 XDOCKER_MAKE_VERSION=development
 
 function log() {
-        echo >&2 -e "[$(date +"%Y-%m-%d %H:%M:%S")] ${1-}"
+	echo >&2 -e "[$(date +"%Y-%m-%d %H:%M:%S")] ${1-}"
 }
 function die() {
-        local msg=$1
-        local code=${2-1} # Bash parameter expansion - default exit status 1. See https://wiki.bash-hackers.org/syntax/pe#use_a_default_value
-        log "$msg"
+	local msg=$1
+	local code=${2-1} # Bash parameter expansion - default exit status 1. See https://wiki.bash-hackers.org/syntax/pe#use_a_default_value
+	log "$msg"
 	if [ "$code" -ne 0 ]; then
 		log "💥 Error!"
 	fi
-        exit "$code"
+	exit "$code"
 }
 
 
@@ -61,10 +61,10 @@ shift 1
 # mount user home dir in container
 DOCKER_BUILD_USER=$(id -u -n)
 DOCKER_USER_HOMEDIR=/home/${DOCKER_BUILD_USER}
-if [ -d ${DOCKER_USER_HOMEDIR} ]; then
-OS_DOCKER_USER_HOMEDIR=${DOCKER_USER_HOMEDIR}
+if [ -d "${DOCKER_USER_HOMEDIR}" ]; then
+OS_DOCKER_USER_HOMEDIR="${DOCKER_USER_HOMEDIR}"
 else
-OS_DOCKER_USER_HOMEDIR=/Users/${DOCKER_BUILD_USER}
+OS_DOCKER_USER_HOMEDIR="/Users/${DOCKER_BUILD_USER}"
 fi
 PROJECT_SRC_DOCKER_DIR=${DOCKER_USER_HOMEDIR}/$(realpath --relative-to="${OS_DOCKER_USER_HOMEDIR}" .)
 
